baseurl = "https://jalan.io/"
disable404 = true
disableRSS = true
disableSitemap = true
relativeURLs = true
title = "jalan.io"

[blackfriday]
  smartypants = false

[params]
  author = "Jason Alan Palmer"
